### ISSUE TITLE
Unable to create a millisecond-precise Snowflake ID

### ISSUE THREAD

**Issue by dmtucker** [client9/snowflake2time#4]
``` python
def utc2snowflake(stamp):
    return ((stamp * 1000) - 1288834974657) << 22
```
```
>>> utc2snowflake(1394885284.050)                                                  
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "snowflake.py", line 20, in utc2snowflake
    return ((stamp * 1000) - 1288834974657) << 22
TypeError: unsupported operand type(s) for <<: 'float' and 'int'
```

If we break this down:
```
>>> 1394885284.050 * 1000
1394885284050.0
>>> 1394885284050.0 - 1288834974657
106050309393.0
>>> 106050309393.0 << 22
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for <<: 'float' and 'int'
```

I think the solution is to round ```(stamp * 1000)``` to an integer like so:
``` python
def utc2snowflake(stamp):
    return (int(round(stamp * 1000)) - 1288834974657) << 22

**Comment by client9** [comment]
I'll gladly accept a pull request here.
